import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="About the Mayer Archive" color="blue" />
      <Hero background="hero-bg-01.svg">
        <h1 className="hero__title">About the Mayer Archive</h1>
      </Hero>
    </>
  );
}
